/*
 * CodeCharacter API
 *
 * Specification of the CodeCharacter API
 *
 * The version of the OpenAPI document: 2022.0.1
 * Contact: delta@nitt.edu
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace CodeCharacter.CoreLibrary.Models
{
    /// <summary>
    ///     Game log model
    /// </summary>
    [DataContract]
    public class GameLogDto : IEquatable<GameLogDto>
    {
        /// <summary>
        ///     Gets or Sets GameLogCompressed
        /// </summary>
        [Required]
        [DataMember(Name = "gameLogCompressed", EmitDefaultValue = false)]
        public string GameLogCompressed { get; set; }

        /// <summary>
        ///     Gets or Sets Player1LogCompressed
        /// </summary>
        [Required]
        [DataMember(Name = "player1LogCompressed", EmitDefaultValue = false)]
        public string Player1LogCompressed { get; set; }

        /// <summary>
        ///     Gets or Sets Player2LogCompressed
        /// </summary>
        [Required]
        [DataMember(Name = "player2LogCompressed", EmitDefaultValue = false)]
        public string Player2LogCompressed { get; set; }

        /// <summary>
        ///     Returns true if GameLogDto instances are equal
        /// </summary>
        /// <param name="other">Instance of GameLogDto to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(GameLogDto other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return
                (
                    GameLogCompressed == other.GameLogCompressed ||
                    GameLogCompressed != null &&
                    GameLogCompressed.Equals(other.GameLogCompressed)
                ) &&
                (
                    Player1LogCompressed == other.Player1LogCompressed ||
                    Player1LogCompressed != null &&
                    Player1LogCompressed.Equals(other.Player1LogCompressed)
                ) &&
                (
                    Player2LogCompressed == other.Player2LogCompressed ||
                    Player2LogCompressed != null &&
                    Player2LogCompressed.Equals(other.Player2LogCompressed)
                );
        }

        /// <summary>
        ///     Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class GameLogDto {\n");
            sb.Append("  GameLogCompressed: ").Append(GameLogCompressed).Append("\n");
            sb.Append("  Player1LogCompressed: ").Append(Player1LogCompressed).Append("\n");
            sb.Append("  Player2LogCompressed: ").Append(Player2LogCompressed).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        ///     Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        ///     Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((GameLogDto) obj);
        }

        /// <summary>
        ///     Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                if (GameLogCompressed != null)
                    hashCode = hashCode * 59 + GameLogCompressed.GetHashCode();
                if (Player1LogCompressed != null)
                    hashCode = hashCode * 59 + Player1LogCompressed.GetHashCode();
                if (Player2LogCompressed != null)
                    hashCode = hashCode * 59 + Player2LogCompressed.GetHashCode();
                return hashCode;
            }
        }

        #region Operators

#pragma warning disable 1591

        public static bool operator ==(GameLogDto left, GameLogDto right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(GameLogDto left, GameLogDto right)
        {
            return !Equals(left, right);
        }

#pragma warning restore 1591

        #endregion Operators
    }
}