/*
 * CodeCharacter API
 *
 * Specification of the CodeCharacter API
 *
 * The version of the OpenAPI document: 2022.0.1
 * Contact: delta@nitt.edu
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Threading.Tasks;
using CodeCharacter.CoreLibrary.Attributes;
using CodeCharacter.CoreLibrary.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace CodeCharacter.CoreLibrary.Controllers;

/// <summary>
/// </summary>
[ApiController]
public abstract class CodeApiController : ControllerBase
{
    /// <summary>
    ///     Create code revision
    /// </summary>
    /// <remarks>Create code revision</remarks>
    /// <param name="createCodeRevisionRequestDto"></param>
    /// <response code="204">No Content</response>
    /// <response code="401">Unauthorized</response>
    /// <response code="422">Unprocessable Entity</response>
    [HttpPost]
    [Route("/user/code/revisions")]
    [Authorize]
    [Consumes("application/json")]
    [ValidateModelState]
    public abstract Task<IActionResult> CreateCodeRevision(
        [FromBody] CreateCodeRevisionRequestDto createCodeRevisionRequestDto);

    /// <summary>
    ///     Get code revision by ID
    /// </summary>
    /// <remarks>Get code revision by ID</remarks>
    /// <param name="revisionId">ID of the code revision</param>
    /// <response code="200">OK</response>
    /// <response code="401">Unauthorized</response>
    /// <response code="404">Not Found</response>
    [HttpGet]
    [Route("/user/code/revisions/{revisionId}")]
    [Authorize]
    [ValidateModelState]
    [ProducesResponseType(statusCode: 200, type: typeof(CodeRevisionDto))]
    public abstract Task<IActionResult>
        GetCodeRevisionById([FromRoute(Name = "revisionId")][Required] Guid revisionId);

    /// <summary>
    ///     Get code revisions
    /// </summary>
    /// <remarks>Get list of all code revision IDs</remarks>
    /// <response code="200">OK</response>
    /// <response code="401">Unauthorized</response>
    [HttpGet]
    [Route("/user/code/revisions")]
    [Authorize]
    [ValidateModelState]
    [ProducesResponseType(statusCode: 200, type: typeof(List<CodeRevisionDto>))]
    public abstract Task<IActionResult> GetCodeRevisions();

    /// <summary>
    ///     Get latest code
    /// </summary>
    /// <remarks>Get latest code</remarks>
    /// <response code="200">OK</response>
    /// <response code="401">Unauthorized</response>
    [HttpGet]
    [Route("/user/code/latest")]
    [Authorize]
    [ValidateModelState]
    [ProducesResponseType(statusCode: 200, type: typeof(CodeDto))]
    public abstract Task<IActionResult> GetLatestCode();

    /// <summary>
    ///     Update latest code
    /// </summary>
    /// <remarks>Update latest code</remarks>
    /// <param name="updateLatestCodeRequestDto"></param>
    /// <response code="204">No Content</response>
    /// <response code="401">Unauthorized</response>
    /// <response code="422">Unprocessable Entity</response>
    [HttpPost]
    [Route("/user/code/latest")]
    [Authorize]
    [Consumes("application/json")]
    [ValidateModelState]
    public abstract Task<IActionResult> UpdateLatestCode(
        [FromBody] UpdateLatestCodeRequestDto updateLatestCodeRequestDto);
}