/*
 * CodeCharacter API
 *
 * Specification of the CodeCharacter API
 *
 * The version of the OpenAPI document: 2022.0.1
 * Contact: delta@nitt.edu
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.ComponentModel.DataAnnotations;
using System.Threading.Tasks;
using CodeCharacter.CoreLibrary.Attributes;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace CodeCharacter.CoreLibrary.Controllers;

/// <summary>
/// </summary>
[ApiController]
public abstract class GameApiController : ControllerBase
{
    /// <summary>
    ///     Get game logs by game ID
    /// </summary>
    /// <remarks>Get game logs by game ID</remarks>
    /// <param name="gameId">UUID of the game</param>
    /// <response code="200">OK</response>
    [HttpGet]
    [Route("/games/{gameId}/logs")]
    [Authorize]
    [ValidateModelState]
    [ProducesResponseType(statusCode: 200, type: typeof(string))]
    public abstract Task<IActionResult> GetGameLogsByGameId([FromRoute(Name = "gameId")] [Required] Guid gameId);
}