name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-coverage:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - uses: actions/cache@v2
        id: cache-nuget
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json', '.config/dotnet-tools.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-
      - name: Restore dependencies
        run: dotnet restore CodeCharacter.sln && dotnet tool restore
      - name: Build
        run: dotnet build --no-restore CodeCharacter.sln
      - name: Test
        run: dotnet test --no-build --collect:"XPlat Code Coverage" --settings CodeCoverage.runsettings CodeCharacter.sln
      - name: Upload coverage
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Generate report
        run: dotnet reportgenerator "-reports:**/coverage.opencover.xml" "-targetdir:docs/coverage" -reporttypes:HtmlInline_AzurePipelines_Dark "-title:CodeCharacter Coverage"
      - name: Push coverage report
        run: |
          git config --local user.email "github-actions@github.com"
          git config --local user.name "github-actions"
          git branch -D gh-pages || echo "Branch does not exist"
          git checkout --orphan gh-pages
          git rm --cached $(git ls-files)
          git add docs/*
          git commit -m "Update docs"
          git push -f origin gh-pages
